<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_checkout_info</name>
   <tag></tag>
   <elementGuidId>a3652455-61a9-444b-a910-af6c0a748c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.checkout_info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkout_info ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>322b7f47-ea0a-40f9-87fe-9b66fc7df848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout_info</value>
      <webElementGuid>e8d393d6-5d83-471e-bb3c-63583056be48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-97406a13a390d7a5b6a56def174bfdf6</value>
      <webElementGuid>4688e088-60a5-4b4b-a1e0-2b9c6287bf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkout_info ')]</value>
      <webElementGuid>ad574dc5-f657-4c6c-834e-29b10a24df1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkout_info ')]</value>
      <webElementGuid>ea495886-1876-4d7f-8bb5-362b004c5e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
