<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Footer Note</name>
   <tag></tag>
   <elementGuidId>c2761ab7-0548-4e01-82d4-39ebe88c1dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.footer_copy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08b31d5e-a7bf-4e7c-9bfb-21d7b87eb27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_copy</value>
      <webElementGuid>68c8875f-6013-4bd4-a452-760d430bddfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>footer-copy</value>
      <webElementGuid>2918d63b-49d1-4864-bb85-fb8f77ea0f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>© 2026 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy</value>
      <webElementGuid>7c262f1c-73c2-46d3-a048-c9ff341e1ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer_copy&quot;]</value>
      <webElementGuid>9b181121-5cfd-4460-af06-7d78233e5654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer/div</value>
      <webElementGuid>5ce5a86a-ce55-4d96-91b8-deeddcd80db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[1]/following::div[1]</value>
      <webElementGuid>90e4d8cb-8acc-46ae-9631-ebfc2adaace5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::div[1]</value>
      <webElementGuid>c0ca3765-90c8-46d9-ab11-f11bc8b43fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='©']/parent::*</value>
      <webElementGuid>c061e399-ff00-443b-b240-cdcae1642d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div</value>
      <webElementGuid>86077bf1-608e-4708-88fe-bf3f3ed9c6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '© 2026 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy' or . = '© 2026 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy')]</value>
      <webElementGuid>2eb9f7e5-d980-4d11-a136-4b113236342f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
